spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: 'kafka.retro.io'
            bindings:
                logEvents:
                    destination: todos-logs
                errorEvents:
                    destination: todos-errors
                containerMetricEvents:
                    destination: todos-container-metrics
cf:
    api: api.sys.retro.io
    username: corbs
    password: howdy
    organization: retro
    space: arcade
    domain: apps.retro.io
    skipSslValidation: true