cf:
  api: changeme
  username: changeme
  password: changeme
  organization: changeme
  space: changeme
  domain: changeme
  skipSslValidation: false
destinations:
  log-events: todos-logs
  container-metric-events: todos-container-metrics
  error-events: todos-errors
spring:
    cloud:
        stream:
            bindings:
                logEvents:
                    destination: ${destinations.log-events}
                errorEvents:
                    destination: ${destinations.error-events}
                containerMetricEvents:
                    destination: ${destinations.container-metric-events}