spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: 'kafka.retro.io'
#                    configuration:
#                        sasl:
#                            mechanism: PLAIN
#                            jaas:
#                                config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=test password=test123;'
#                        security:
#                            protocol: SASL_PLAINTEXT
