spring:
  application:
    name: 'todos-webui'
  thymeleaf:
    cache: false
  security:
    user:
      name: Nacho
todos:
  webui:
    placeholder: "Time to wash the dog?"
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    io.todos: INFO
