spring:
  application:
    name: todos-webclient
logging:
  level:
    io.todos: DEBUG
server:
    port: 8009
management:
  endpoints:
    web:
      exposure:
        include: '*'
todos:
  api:
    service: 'http://TODOS-API'