spring:
  application:
    name: todos-shell
jars:
  folder: .apps/jars
cf:
  api: api.sys.retro.io
  username: corbs
  password: howdy
  organization: retro
  space: arcade
  domain: apps.retro.io
  skipSslValidation: true

