spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: 'kafka.retro.io'
            bindings:
                output:
                    destination: todos
