spring:
  application:
    name: todos-restclient
logging:
  level:
    io.todos: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
todos:
  api:
    endpoint: http://localhost:8080

